services:
  homepage:
    build:
      context: ./homepage
    image: tracker/homepage:latest
    ports:
      - "8070:80"
    restart: unless-stopped

  wiki:
    build:
      context: ./homepage
      dockerfile: wiki/Dockerfile
    image: tracker/wiki:latest
    ports:
      - "8072:80"
    restart: unless-stopped

  webapp:
    build:
      context: ./app
      dockerfile: Dockerfile.web
      args:
        BACKEND_URL: https://api.personal-tracker.life
    image: tracker/webapp:latest
    ports:
      - "8071:80"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: tracker
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: tracker
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal
    restart: unless-stopped

  backend:
    build:
      context: ./backend_dart
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://tracker:tracker@db:5432/tracker
      AUTH_SECRET_KEY: change-this-secret
      CORS_ALLOW_ORIGINS: "https://app.personal-tracker.life,https://personal-tracker.life,https://www.personal-tracker.life"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8073:8080"
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    internal: true
