version: "3.9"

services:
  homepage:
    build:
      context: ./homepage
    image: tracker/homepage:latest
    ports:
      - "8080:80"

  webapp:
    build:
      context: ./app
      dockerfile: Dockerfile.web
    image: tracker/webapp:latest
    ports:
      - "8081:80"
