services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: tracker
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: tracker
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend_dart
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://tracker:tracker@db:5432/tracker
      AUTH_SECRET_KEY: change-this-secret
      CORS_ALLOW_ORIGINS: "*"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  tracker-postgres-data:
