services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tracker_backend
      POSTGRES_PASSWORD: "-Gic3hIeDfWt4Z4pBAOV2jLfC3Q-Eack"
    tmpfs:
      - /var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "VDoLpTYKUuz4kEC1bSg7dksuZ33EIsws"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tracker_backend_test
      POSTGRES_PASSWORD: "mdihC5D8I8OF4LEBSCY7NqOC0mOd2LLb"
    tmpfs:
      - /var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "OmqJ8YWt0Pe85JbEw-bOATSrKNNDnzRp"
    environment:
      - REDIS_REPLICATION_MODE=master
