FROM ghcr.io/cirruslabs/flutter:3.32.8 as builder
ARG BACKEND_URL=https://api.personal-tracker.life
ENV BACKEND_URL=${BACKEND_URL}
WORKDIR /build
COPY . .
RUN flutter pub get \
    && flutter build web --release --dart-define=BACKEND_URL=$BACKEND_URL

FROM nginx:alpine
COPY --from=builder /build/build/web /usr/share/nginx/html
